# Generated by Django 4.1 on 2022-08-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empregador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('qualificacao', models.CharField(max_length=100)),
                ('salario', models.IntegerField()),
                ('empregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregador.empregador')),
            ],
        ),
    ]
